vich_uploader:
    db_driver: orm
    mappings:
        image_upload:
            uri_prefix: '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_images%'
            delete_on_remove: true
            delete_on_update: true
